// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWKj_vb8Yr7YktEjSto4T0dysOdMJA0aY',
    appId: '1:907817689427:web:9c55a98d5a310a5dc781a6',
    messagingSenderId: '907817689427',
    projectId: 'four-thirty',
    authDomain: 'four-thirty.firebaseapp.com',
    storageBucket: 'four-thirty.firebasestorage.app',
    measurementId: 'G-0JZ6M56NB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MFtLicGKHM1oB5_aHTDppD63oYZVaYA',
    appId: '1:907817689427:android:73f001fa0ff1074fc781a6',
    messagingSenderId: '907817689427',
    projectId: 'four-thirty',
    storageBucket: 'four-thirty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdQDsvRo19HYltCgM7XG71t2HCErQwZKI',
    appId: '1:907817689427:ios:9178cc49231ab868c781a6',
    messagingSenderId: '907817689427',
    projectId: 'four-thirty',
    storageBucket: 'four-thirty.firebasestorage.app',
    androidClientId: '907817689427-dkh8ac6svm3olcta9lint09940scp221.apps.googleusercontent.com',
    iosClientId: '907817689427-jd9v6ca3lrk7h162hetmm547lsak37jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fourthirty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdQDsvRo19HYltCgM7XG71t2HCErQwZKI',
    appId: '1:907817689427:ios:9178cc49231ab868c781a6',
    messagingSenderId: '907817689427',
    projectId: 'four-thirty',
    storageBucket: 'four-thirty.firebasestorage.app',
    androidClientId: '907817689427-dkh8ac6svm3olcta9lint09940scp221.apps.googleusercontent.com',
    iosClientId: '907817689427-jd9v6ca3lrk7h162hetmm547lsak37jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fourthirty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWKj_vb8Yr7YktEjSto4T0dysOdMJA0aY',
    appId: '1:907817689427:web:d6ed93f2bdd1898ac781a6',
    messagingSenderId: '907817689427',
    projectId: 'four-thirty',
    authDomain: 'four-thirty.firebaseapp.com',
    storageBucket: 'four-thirty.firebasestorage.app',
    measurementId: 'G-M2L1THB02J',
  );

}
